// Generated by gencpp from file ecm_bridge/driverCmd.msg
// DO NOT EDIT!


#ifndef ECM_BRIDGE_MESSAGE_DRIVERCMD_H
#define ECM_BRIDGE_MESSAGE_DRIVERCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ecm_bridge
{
template <class ContainerAllocator>
struct driverCmd_
{
  typedef driverCmd_<ContainerAllocator> Type;

  driverCmd_()
    : enable()
    , opMode()
    , kp()
    , kd()
    , q()
    , qd()
    , cur()  {
    }
  driverCmd_(const ContainerAllocator& _alloc)
    : enable(_alloc)
    , opMode(_alloc)
    , kp(_alloc)
    , kd(_alloc)
    , q(_alloc)
    , qd(_alloc)
    , cur(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _enable_type;
  _enable_type enable;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _opMode_type;
  _opMode_type opMode;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _kp_type;
  _kp_type kp;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _kd_type;
  _kd_type kd;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _q_type;
  _q_type q;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _qd_type;
  _qd_type qd;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cur_type;
  _cur_type cur;





  typedef boost::shared_ptr< ::ecm_bridge::driverCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ecm_bridge::driverCmd_<ContainerAllocator> const> ConstPtr;

}; // struct driverCmd_

typedef ::ecm_bridge::driverCmd_<std::allocator<void> > driverCmd;

typedef boost::shared_ptr< ::ecm_bridge::driverCmd > driverCmdPtr;
typedef boost::shared_ptr< ::ecm_bridge::driverCmd const> driverCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ecm_bridge::driverCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ecm_bridge::driverCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ecm_bridge::driverCmd_<ContainerAllocator1> & lhs, const ::ecm_bridge::driverCmd_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable &&
    lhs.opMode == rhs.opMode &&
    lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd &&
    lhs.q == rhs.q &&
    lhs.qd == rhs.qd &&
    lhs.cur == rhs.cur;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ecm_bridge::driverCmd_<ContainerAllocator1> & lhs, const ::ecm_bridge::driverCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ecm_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ecm_bridge::driverCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ecm_bridge::driverCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ecm_bridge::driverCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ecm_bridge::driverCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecm_bridge::driverCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ecm_bridge::driverCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ecm_bridge::driverCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ac7643f368fa7335ff4aa8b3f789c47";
  }

  static const char* value(const ::ecm_bridge::driverCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ac7643f368fa733ULL;
  static const uint64_t static_value2 = 0x5ff4aa8b3f789c47ULL;
};

template<class ContainerAllocator>
struct DataType< ::ecm_bridge::driverCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecm_bridge/driverCmd";
  }

  static const char* value(const ::ecm_bridge::driverCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ecm_bridge::driverCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] enable\n"
"uint8[] opMode\n"
"float64[] kp\n"
"float64[] kd\n"
"float64[] q\n"
"float64[] qd\n"
"float64[] cur\n"
"\n"
;
  }

  static const char* value(const ::ecm_bridge::driverCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ecm_bridge::driverCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
      stream.next(m.opMode);
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.q);
      stream.next(m.qd);
      stream.next(m.cur);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct driverCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ecm_bridge::driverCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ecm_bridge::driverCmd_<ContainerAllocator>& v)
  {
    s << indent << "enable[]" << std::endl;
    for (size_t i = 0; i < v.enable.size(); ++i)
    {
      s << indent << "  enable[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.enable[i]);
    }
    s << indent << "opMode[]" << std::endl;
    for (size_t i = 0; i < v.opMode.size(); ++i)
    {
      s << indent << "  opMode[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.opMode[i]);
    }
    s << indent << "kp[]" << std::endl;
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      s << indent << "  kp[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.kp[i]);
    }
    s << indent << "kd[]" << std::endl;
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      s << indent << "  kd[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.kd[i]);
    }
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "qd[]" << std::endl;
    for (size_t i = 0; i < v.qd.size(); ++i)
    {
      s << indent << "  qd[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.qd[i]);
    }
    s << indent << "cur[]" << std::endl;
    for (size_t i = 0; i < v.cur.size(); ++i)
    {
      s << indent << "  cur[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cur[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ECM_BRIDGE_MESSAGE_DRIVERCMD_H
