# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_control/rover.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class rover(genpy.Message):
  _md5sum = "8939377560b48465bde83d9b3af7dfb7"
  _type = "car_control/rover"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 rover_px
float64 rover_py
float64 rover_vx
float64 rover_vy
float64 rover_w
int32 rover_state"""
  __slots__ = ['rover_px','rover_py','rover_vx','rover_vy','rover_w','rover_state']
  _slot_types = ['float64','float64','float64','float64','float64','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rover_px,rover_py,rover_vx,rover_vy,rover_w,rover_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(rover, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rover_px is None:
        self.rover_px = 0.
      if self.rover_py is None:
        self.rover_py = 0.
      if self.rover_vx is None:
        self.rover_vx = 0.
      if self.rover_vy is None:
        self.rover_vy = 0.
      if self.rover_w is None:
        self.rover_w = 0.
      if self.rover_state is None:
        self.rover_state = 0
    else:
      self.rover_px = 0.
      self.rover_py = 0.
      self.rover_vx = 0.
      self.rover_vy = 0.
      self.rover_w = 0.
      self.rover_state = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5di().pack(_x.rover_px, _x.rover_py, _x.rover_vx, _x.rover_vy, _x.rover_w, _x.rover_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 44
      (_x.rover_px, _x.rover_py, _x.rover_vx, _x.rover_vy, _x.rover_w, _x.rover_state,) = _get_struct_5di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5di().pack(_x.rover_px, _x.rover_py, _x.rover_vx, _x.rover_vy, _x.rover_w, _x.rover_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 44
      (_x.rover_px, _x.rover_py, _x.rover_vx, _x.rover_vy, _x.rover_w, _x.rover_state,) = _get_struct_5di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5di = None
def _get_struct_5di():
    global _struct_5di
    if _struct_5di is None:
        _struct_5di = struct.Struct("<5di")
    return _struct_5di
