(cl:in-package car_control-msg)
(cl:export '(WHEEL_POS_ACTUAL-VAL
          WHEEL_POS_ACTUAL
          WHEEL_POS_DESIRED-VAL
          WHEEL_POS_DESIRED
          WHEEL_VEL_ACTUAL-VAL
          WHEEL_VEL_ACTUAL
          WHEEL_VEL_DESIRED-VAL
          WHEEL_VEL_DESIRED
          STEER_POS_ACTUAL-VAL
          STEER_POS_ACTUAL
          STEER_POS_DESIRED-VAL
          STEER_POS_DESIRED
          STEER_VEL_ACTUAL-VAL
          STEER_VEL_ACTUAL
          STEER_VEL_DESIRED-VAL
          STEER_VEL_DESIRED
))